apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nodepool.fullname" . }}
  labels:
    app: {{ template "nodepool.name" . }}
    chart: {{ template "nodepool.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  publicKey: |-
    {{ .Values.ssh.publicKey | b64enc }}
  privateKey: |-
    {{ .Values.ssh.privateKey | b64enc }}
