apiVersion: v1
kind: Service
metadata:
  name: {{ template "zuul.fullname" . }}-gearman
  labels:
    app: {{ template "zuul.name" . }}
    chart: {{ template "zuul.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4730
      targetPort: gearman
      protocol: TCP
      name: gearman
  selector:
    app: {{ template "zuul.name" . }}
    role: gearman
    release: {{ .Release.Name }}
