apiVersion: v1
kind: Service
metadata:
  name: {{ template "nodepool.fullname" . }}-nodes
  labels:
    app: {{ template "nodepool.name" . }}
    chart: {{ template "nodepool.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: "None"
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "nodepool.name" . }}
    role: node
    release: {{ .Release.Name }}
